### PR TITLE
chore(deps): update to @redocly/developer-portal@1.1.0-beta.28

### PR DESCRIPTION
**Pull request by adamaltman**
## What/Why/How?

- Updates dependency to the latest developer portal 
- Cleans up the sidebar (added labels to the various `.page.yaml` files)

## Reference

- https://redoc.ly/docs/developer-portal/guides/migration-guide-1-1-0/

## Testing

- n/a

## Screenshots (optional)

image

## Check yourself

- [ ] Code is linted
- [x] Tested
- [ ] All new/updated code is covered with tests

## Security

- [x] Security impact of change has been considered
- [x] Code follows company security practices and guidelines

### CODE REVIEW

**Comment by adamaltman** [comment]
The new portal detects errors with the OpenAPI definitions. I'll propose fixes for them, or we can add them to an ignore file.

**Comment by pdesjardins** [comment]
This is an interesting PR because it is causing portal builds to fail because of invalid syntax in our OpenAPI specifications. They're real invalid syntax problems, so I'm just fixing them. I'm surprised that builds weren't failing before. Does the latest version of the portal do more validation?

**Review by pdesjardins — APPROVED** [review]
I had to fix some problems with our OpenAPI specifications to make this PR pass the CI builds. But now it's passing! The problems were entirely our fault.

**Comment by pdesjardins** [comment]
Also! Thank you for this contribution, @adamaltman!

**Pull request merged**
