### PR TITLE
Add schema object reference to API documentation site

### PR DESCRIPTION
**Pull request by pdesjardins**
## What/Why/How?

Update Toast Redoc.ly portal version to 1.1.0-beta.106. I am trying to use the schema object reference feature.

https://toasttab.atlassian.net/browse/DOC-2383

## Testing

Take a look at the preview API reference documentation:

https://preview.redoc.ly/toastintegrations/pdesjardins_DOC-2383/

### Verify that the recursive problem is no longer present

Look at the definition for `checks` in the `Order` object: 

[`checks`](https://preview.redoc.ly/toastintegrations/pdesjardins_DOC-2383/orders/operation/ordersGuidGet/)

Make sure it shows the contents of a `Check` object. Previously, using the latest version of the Redoc.ly portal project caused a "recursive" error message for this kind of array-of-objects value.

### Verify that the data definitions sections present data object reference documentation

Look in the reference documentation section for each API. Expand the "data definitions" sections and look at the object documentation in them. Unless there's something really horrible in there, I think we can add this component to the API reference doc. It was an explicit request from some API doc users when we launched the new site.

Screen Shot 2022-08-03 at 12 40 22 AM

### CODE REVIEW

**Comment by janicemanwiller-toast** [comment]
The schema definitions look good in general, and it will definitely be nice to have them. A few things to look at.

It looks like there are only data definitions for the orders API and the partners API. Is that deliberate for initial testing, or should there be data definitions for the other APIs?

Is there a configuration to alphabetize the list of objects under **Data definitions**, similar to what we did with the list of parameters within an object? It's very difficult to scan through a list in random order, especially a long list such as the objects in the orders API.

Mentioned this before, but still noticing it. Whenever a value is a reference to another object or contains an array of objects, it refers to the object but does not either list the values in the object or provide a way to jump to the definition of the object.

OrderChecks

For something like an external reference, which only has a few properties (mainly the GUID), this maybe isn't a big deal. For something like the `Check` object, which is vital to the `Order` object, it's really inconvenient to have to go back to the contents and look for the `Check` object in the data definitions. The `Check` object also contains multiple arrays of objects, such as selections, applied discounts, applied service charges. You have to go digging in the data definitions separately for each one.

**Comment by pdesjardins** [comment]
I missed your comments here, @janicemanwiller-toast. You're totally right about those "recursive" problems not being acceptable. The Redoc.ly team is aware of that and they have a workaround in the branch of the portal product that we're using in production. This preview branch is using the very latest version of the portal product, which does not include our workaround.

**Comment by pdesjardins** [comment]
@toasttab/documentation, @toasttab/integrations, I added the new "data definitions" data object reference sections to all the public APIs.

This is ready for real review now. I think we can merge this and add the new object references to our live API doc.

Implementing the data dictionary in our new site API doc is the last outstanding project before we can finally take the old API doc site down.

**Comment by mickey-toast** [comment]
After better understanding this, I agree that this is valuable, especially for devs. Approving!

**Pull request merged**
